[package]
name = "sdif"
version = "0.1.0"
authors = ["btc <734339+btc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
